### ISSUE TITLE
Error + Disabled when not using economy regardless of towny setting

### ISSUE THREAD

**Issue by 1ByteBit** [thatguycy/WorldDynamics-Engine#6]
When there isn't a compatible economy plugin installed on the server regardless of whether economy is enabled in the towny config, the following lines appear:

`[WorldDynamicsEngine] [WorldDynamicsEngine] - Disabled due to no Vault dependency found!`
Is this trying to say "no plugins depending on vault found"? At first glance, it appears to say "No vault plugin found" which makes it confusing

```Error occurred while disabling WorldDynamicsEngine v0.1.5
java.lang.NullPointerException: Cannot invoke "com.thatguycy.worlddynamicsengine.NationManager.saveNations()" because "this.nationManager" is null
        at com.thatguycy.worlddynamicsengine.WorldDynamicsEngine.onDisable(WorldDynamicsEngine.java:126) ~[WorldDynamicsEngine-0.1.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:225) ~[paper-1.20.4.jar:git-Paper-389]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-389]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.thatguycy.worlddynamicsengine.WorldDynamicsEngine.onEnable(WorldDynamicsEngine.java:41) ~[WorldDynamicsEngine-0.1.5.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-389]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-389]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-389]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-389]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-389]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by thatguycy** [comment]
Hi, odd question but do you have EssentialsX installed, if not could you try installing it and running it like that? Let me know how it goes.

**Comment by thatguycy** [comment]
I believe the issue is in plugin.yml.

Insert the below line anywhere in the plugin.yml, let me know the results and I'll make a pull request tomorrow when I'm at the computer.

```
softdepend: [Vault]
```

**Comment by 1ByteBit** [comment]
I can confirm that having essentialsx fixes the issue, this issue only seems to appear if no economy plugin is installed. Currently checking the possible fix, however your plugin.yml already has Vault listed as a soft depend

**Comment by 1ByteBit** [comment]
For the fix I pretty much just removed the towny from plugin.yml just to double check, and no changes. If there's something else you wish to try, shoot, as I have access to an IDE for testing changes. But past that, I have noticed that other plugins have a similar issue when trying to use vault without an economy plugin

**Comment by thatguycy** [comment]
Hm, I'll try and fix this in the morning, possibly by initializating a custom economy? I'll see.

**Comment by 1ByteBit** [comment]
I know that towny itself manages to work itself out with this exact situation, so you may be able to look at what they do

**Comment by thatguycy** [comment]
Hey, I spoke with LlmDl (Leader Towny Dev) and he told me to check 'TownyEconomyHandler' for inspiration, I'll take a look tonight and make some changes in the morning.
